easy_admin:
    entities:
        Command:
          class: App\Entity\Command
          list:
            - { name: 'show' }
            - { name: 'delete' }
          show:
            actions: ['delete']
        Product:
            class: App\Entity\Product
            list:
                fields: ['id', 'name', 'price', 'description']
            form:
                fields: ['name', 'price', 'description']